### ISSUE TITLE
Add static file directive to nginx config

### ISSUE THREAD

**Issue by AaronHolbrook** [DockerBox/dockerbox#24]
This should be added to the nginx shared.conf.inc so that it doesn't pass along requests to static files to php (which prevents additional pointless processing for php, etc): 

```
location ~* \.(?:ico|css|js|gif|jpe?g|png|svg|woff|ttf|eot)$ {
    expires 6h;
    add_header Pragma public;
    add_header Cache-Control "public";
}```

**Comment by AaronHolbrook** [comment]
I've added above the `/` and php directives in my config:
![](http://d.pr/i/OKP4/5XHYFtbr+)

**Comment by AaronHolbrook** [comment]
Probably need to be smarter about the css/js files as then they get cached too long

**Comment by philipnewcomer** [comment]
@AaronHolbrook I'm confused as to why this is needed. Aren't static files already being served directly without involving PHP?

**Comment by philipnewcomer** [comment]
Okay, I did some investigating and I think it's if the file does not exist that it gets passed to PHP that you were referring to, so we definitely do need this. I also see a similar directive in the [wordpress.org recommended Nginx configuration](https://codex.wordpress.org/Nginx).

However, I wonder, since this is a development environment, would we want any of these files to be cached? Obviously we would want to cache these in production environments, but on dev I'm thinking it'd be better not to cache any of this.

**Comment by AaronHolbrook** [comment]
Yea that's where I was torn, on one hand we don't want to be passing unrealistic requests like favicon.ico continually to the php backend, since during debugging that causes additional fake requests to come in, but on the other hand caching static assets could be very problematic to seeing changes.

**Comment by AaronHolbrook** [comment]
Maybe we should add in the favicon.ico block like the codex has as well

**Comment by AaronHolbrook** [comment]
https://codex.wordpress.org/Nginx#Global_restrictions_file

**Comment by philipnewcomer** [comment]
Good idea; done.

**Comment by philipnewcomer** [comment]
Hmmm; looks like the static file directive is conflicting with image proxying from production. Reopening to investigate that.

**Comment by philipnewcomer** [comment]
Proxying was working fine; but all static assets were being proxied. Now only proxying image files, and only image files in an uploads directory.
